name: CI

on: push

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  MIX_ENV: test
  OTP_VERSION: '25.1.2'
  ELIXIR_VERSION: '1.14.2'

jobs:
  workflow:
    name: Workflow
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ env.OTP_VERSION }}
          elixir-version: ${{ env.ELIXIR_VERSION }}

      - name: Set up cache
        uses: actions/cache@v4
        id: mix-cache
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-mix-${{ env.OTP_VERSION }}-${{ env.ELIXIR_VERSION }}-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-

      - name: Get deps
        if: steps.mix-cache.outputs.cache-hit != 'true'
        run: mix deps.get

      - name: Compile deps
        if: steps.mix-cache.outputs.cache-hit != 'true'
        run: mix deps.compile

      # - name: Build Dialyzer PLT(s)
      #   if: steps.mix-cache.outputs.cache-hit != 'true'
      #   run: mix dialyzer --plt

      - name: Mix compile
        run: mix compile --force --warnings-as-errors

      - name: Mix format
        run: mix format --check-formatted

      # - name: Credo
      #   run: mix credo --all

      # - name: Dialyzer
      #   run: mix dialyzer --no-check

      - name: Mix test
        run: mix test
